config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'projects/index'
  devise_for :users
  root "home#index"
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :projects

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_rich_text :body
    has_many_attached :images
    has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to root_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :user_id, :body, :file, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/_header.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-auto">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to 'Project App', root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Projects', projects_path, class:"nav-link active" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign out',  destroy_user_session_path, class:"nav-link", method: :delete %>
                </li>
                <li class="nav-item">
                  <%= link_to "Edit", edit_user_registration_path, class:"nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<!-- Add row, col -->
<div class="row justify-content-md-center">
    <div class="col-md-auto">

        <h1>My Basecamp 1</h1>

    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>MyBasecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = "container">
      <br>
      <div class="row justify-content-center">
        <br/>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="col-auto">

  <%= form_with model: project do |form| %>
    <div class ="mb-3">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control" %>
      <% project.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.rich_text_area :body %>
    </div>

    <!-- File -->
    <!-- >
    <div class="field">
      <%= form.label :file %>
      <%= form.file_field :file %>
    </div>
    <-->

    <br>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="col-auto">
  <h1>Edit Project</h1>

  <%= render "form", project: @project %>
</div>

app/views/projects/index.html.erb
<div class="col-auto">
  <h1>Projects</h1>
  <br>
</div>

<div class="row justify-content-center">
  <% @projects.each do |project| %>
    <% if project.user == current_user %>
      <div class="col-auto">
        <div class="card text-dark bg-light mb-3" style="width: 18rem;">
          <div class="card-header text-white bg-secondary mb-3">
            <h5><%= project.name %></h5>
          </div>
          <div class="card-body text-dark bg-light mb-3">
              <h5 class="card-title"><% project.name %></h5>
              <h6 class="card-subtitle"></h6>
              <p class="card-text"><%= project.body %></p>
              <a href="#" class="card-link"><%= link_to "Show", project %></a>
              <a href="#" class="card-link"><%= link_to "Edit", edit_project_path(project) %></a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="col-auto">
  <%= link_to "New Project", new_project_path, class:"btn btn-primary" %>
</div>

app/views/projects/new.html.erb
<div class="col-auto">
  <h1>New Project</h1>

  <%= render "form", project: @project %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-auto">

  <h1><%= @project.name %></h1>
  <br>

  <%= @project.body %>
  
  <br>

  <!-- >
  <%= form_with model: @project do |form| %>
    <div class="field">
      <%= form.label :file %>
      <%= form.file_field :file, class: "form-control" %>
    </div>
  <% end %>
  <-->
  
  <ul>
    <%= link_to "Edit", edit_project_path(@project), class:"btn btn-primary" %>
    <%= link_to "Delete", project_path(@project), class:"btn btn-primary",
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
  </ul>

</div>